### ISSUE TITLE
Quick CSS fixes

### ISSUE THREAD

**Issue by cmhainje** [kathrynleung/kathrynleung.github.io#1]
The bootstrap "row" class has `margin-left: -15px` and `margin-right: -15px`, which, when used in the root of the body component, seems to create a small horizontal overflow. CSS fix:

```css
.row {
    margin-left: 0;
    margin-right: 0;
}
```

Also, consider adding a fallback font for users who don't have Futura installed. Specify it like this:
```css
body {
    font-family: Futura, sans-serif !important;
}
```
(e.g. add sans-serif after Futura)
